Generate a Fake Employee Dataset

In [1]:
# You must run this code and use this dataset for all questions

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

Use  NumPy arrays ,  the emp_ages and emp_income. 
 Print both arrays and display: 
● data type 
● number of dimensions 
● shape 
● total number of elements

In [7]:
#emp_ages:
print('Employee Ages:')
print('Data Type:',emp_ages.dtype)
print('Number of Dimensions:',emp_ages.ndim)
print('Shape:',emp_ages.shape)
print('Total Number of Elements:',emp_ages.size)


#emp_income:
print('Employee Incomes:')
print('Data type:',emp_income.dtype)
print('Number of Dimensions:',emp_income.ndim)
print('Shape:',emp_income.shape)
print('Total Number of Elements:',emp_income.size)

Employee Ages:
Data Type: int32
Number of Dimensions: 1
Shape: (50,)
Total Number of Elements: 50
Employee Incomes:
Data type: int32
Number of Dimensions: 1
Shape: (50,)
Total Number of Elements: 50

Using NumPy functions: 
● Find the maximum and minimum salary 
● Calculate the average salary 
● Calculate the average age 
Print all results.

In [10]:
a= np.max(emp_income)
b= np.min(emp_income)
c= np.mean(emp_income)
d= np.mean(emp_ages)
print('Maximum Salary:',a)
print('Minimum Salary:',b)
print('Average Salary:',c)
print('Average Age:',d)

Maximum Salary: 94722
Minimum Salary: 35452
Average Salary: 68409.48
Average Age: 35.44

From the emp_ages array: 
Extract employees who: 
● are aged between 25 and 40, 
AND 
Emp_salary : have salary greater than 50,000 
Then :  
● Print the filtered values 
● Count how many employees satisfy this condition

In [19]:
A= (emp_ages>=25) & (emp_ages<=40) & (emp_income>50000)
B= emp_ages[A]
C= np.sum(A)
print('Filtered Values by Age:',B)
print('Number of Satisfy Employee:', C)

Filtered Values by Age: [37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
Number of Satisfy Employee: 17

Create a new NumPy array where each employee’s age is adjusted based on: 
● Add 4 years if age is less than the average age 
● Add 2 years if age is greater than or equal to the average age 
Do NOT modify the original array. 
Print: 
● original array 
● updated array 
● average age used for condition

In [22]:
a= np.mean(emp_ages)
update= np.where(emp_ages<a,emp_ages+4,emp_ages+2)
print('Original Array',emp_ages)
print('Updated Array',update)
print('Average age used for condition',a)

Original Array [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Updated Array [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
Average age used for condition 35.44

Using NumPy: 
● Assume all salaries of Tech roles increase by 8% 
● Calculate the new total salary expense 
● Find the overall increase in expense after the raise 
Print both old and new totals along with the difference

In [24]:
a= np.sum(emp_income)
tech= ((emp_roles=="Software Developer") | (emp_roles=="Backend Developer"))
update= np.where(tech, emp_income*1.08, emp_income)
b= np.sum(update)
diff= b-a
print('Old Total Salaries:',a)
print('New Total Salaries:',b)
print('Difference Between Old and New Salaries:',diff)

Old Total Salaries: 3420474
New Total Salaries: 3490246.0
Difference Between Old and New Salaries: 69772.0

Load the staff_data.csv file into a Pandas DataFrame. 
● Display the first 3 rows 
● Show dataset information using .info() 
● Display summary statistics using .describe()

In [27]:
a= pd.read_csv('staff_data.csv')
a.head(3)
a.info()
a.describe()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     str
dtypes: int64(3), str(1)
memory usage: 2.4 KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

Filter the dataset to include only: 
● emp_id, emp_age, role 
Then: 
● Select employees whose age is between 25 and 40 
● Sort them by emp_id 
● Display the last 3 rows of the result

In [30]:
a[['emp_id','emp_age','role']]
flt= a[(a['emp_age']>=25) & (a['emp_age']<=40)]
flt.sort_values('emp_id')
flt.tail(3)

    emp_id  emp_age  emp_salary                 role
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
48     149       31       59727     Digital Marketer

Filter the DataFrame to show only employees working in the "HR" role. 
● Print the filtered data 
● Show the total number of HR employees

In [33]:
hr= a[a['role'].str.contains('HR')]
len(hr)

9

Sort the DataFrame by: 
● emp_age (ascending) 
● and then by emp_salary (descending) 
Display the top 5 employees after sorting, including: 
● emp_id 
● role 
● emp_salary

In [35]:
b= a.sort_values(by=['emp_age','emp_salary'], ascending=[True,False] )
b.head(5)

    emp_id  emp_age  emp_salary                role
30     131       20       82550     Sales Executive
18     119       20       63187  Software Developer
41     142       20       59500    Digital Marketer
2      103       20       35452  Operations Manager
36     137       21       94427     Sales Executive

Using .loc: 
● Increase salary by 12% for "Software Developer" and "Backend Developer" 
● Increase salary by 5% for all other roles 
Then: 
● Print the dataframe that includes role , previous_salary , new_salary , increase_of_salary

In [38]:
a['emp_salary'] = a['emp_salary'].astype(float)
a['previous_salary'] = a['emp_salary']
tech= ((a['role']=='Software Developer') | (a['role']=='Backend Developer'))
a.loc[tech,'emp_salary'] *= 1.12
a.loc[~tech,'emp_salary'] *= 1.05
a['increase_of_salary'] = ( a['emp_salary'] - a['previous_salary'] )
print(a[['role' , 'previous_salary' , 'emp_salary' , 'increase_of_salary']])

                   role  previous_salary  emp_salary  increase_of_salary
0            HR Manager          51725.0    54311.25             2586.25
1            Accountant          38495.0    40419.75             1924.75
2    Operations Manager          35452.0    37224.60             1772.60
3      Digital Marketer          82295.0    86409.75             4114.75
4     Backend Developer          72187.0    80849.44             8662.44
5            HR Manager          58915.0    61860.75             2945.75
6     Backend Developer          76159.0    85298.08             9139.08
7       Sales Executive          92864.0    97507.20             4643.20
8       Sales Executive          76155.0    79962.75             3807.75
9          HR Executive          90494.0    95018.70             4524.70
10    Backend Developer          68641.0    76877.92             8236.92
11  Marketing Executive          48079.0    50482.95             2403.95
12      Sales Executive          56879.0    59722.95             2843.95
13   Operations Manager          83682.0    87866.10             4184.10
14     Digital Marketer          94722.0    99458.10             4736.10
15    Financial Analyst          91041.0    95593.05             4552.05
16      Sales Executive          48899.0    51343.95             2444.95
17   Operations Manager          68744.0    72181.20             3437.20
18   Software Developer          63187.0    70769.44             7582.44
19    Backend Developer          74146.0    83043.52             8897.52
20      Sales Executive          75641.0    79423.05             3782.05
21      Sales Executive          47678.0    50061.90             2383.90
22           Accountant          76760.0    80598.00             3838.00
23   Software Developer          78354.0    87756.48             9402.48
24         HR Executive          60584.0    63613.20             3029.20
25   Operations Manager          79898.0    83892.90             3994.90
26     Digital Marketer          59682.0    62666.10             2984.10
27         HR Executive          71888.0    75482.40             3594.40
28   Software Developer          51086.0    57216.32             6130.32
29           Accountant          73700.0    77385.00             3685.00
30      Sales Executive          82550.0    86677.50             4127.50
31  Marketing Executive          71447.0    75019.35             3572.35
32     Digital Marketer          76100.0    79905.00             3805.00
33    Backend Developer          72269.0    80941.28             8672.28
34   Software Developer          73314.0    82111.68             8797.68
35   Software Developer          87428.0    97919.36            10491.36
36      Sales Executive          94427.0    99148.35             4721.35
37           Accountant          84188.0    88397.40             4209.40
38           HR Manager          52013.0    54613.65             2600.65
39      Sales Executive          63326.0    66492.30             3166.30
40  Marketing Executive          44396.0    46615.80             2219.80
41     Digital Marketer          59500.0    62475.00             2975.00
42         HR Executive          55523.0    58299.15             2776.15
43           Accountant          58602.0    61532.10             2930.10
44         HR Executive          90794.0    95333.70             4539.70
45           HR Manager          41061.0    43114.05             2053.05
46   Software Developer          82331.0    92210.72             9879.72
47   Software Developer          73048.0    81813.76             8765.76
48     Digital Marketer          59727.0    62713.35             2986.35
49  Marketing Executive          50398.0    52917.90             2519.90